spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server.dev.svc.cluster.local:8555

management:
  otlp:
    logging:
      endpoint: http://otel-collector.dev.svc.cluster.local:4318/v1/logs
    metrics:
      export:
        url: http://otel-collector.dev.svc.cluster.local:4318/v1/metrics
    tracing:
      endpoint: http://otel-collector.dev.svc.cluster.local:4318/v1/traces
otel:
  resource:
    attributes:
      deployment.environment: dev