server:
  port: 8300

spring:
  application:
    name: phoenix-product
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8555
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/productdb
    username: admin
    password: password123
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30s
  flyway:
    url: jdbc:postgresql://localhost:5432/productdb
    user: admin
    password: password123
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,loggers
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  otlp:
    logging:
      endpoint: http://localhost:4318/v1/logs
      export:
        enabled: true
      timeout: 10s
    metrics:
      export:
        enabled: true
        url: http://localhost:4318/v1/metrics
    tracing:
      endpoint: http://localhost:4318/v1/traces
      export:
        enabled: true
      timeout: 10s

otel:
  resource:
    attributes:
      service.name: ${spring.application.name}
      service.namespace: phoenix
      deployment.environment: local

# Phoenix Events Configuration
phoenix:
  events:
    topics:
      product-events: product-events
    kafka:
      bootstrap-servers: localhost:9092
      schema-registry:
        url: http://localhost:8081
        connection-timeout-ms: 30000
        read-timeout-ms: 30000
        max-cache-size: 100
        authentication:
          username:
          password:
          bearer-token:
      consumer:
        group-id: test-group
        auto-offset-reset: earliest
        enable-auto-commit: true
        auto-commit-interval: 5000ms
        session-timeout: 30000ms
        heartbeat-interval: 3000ms
        max-poll-records: 500
        max-poll-interval: 300000ms
      producer:
        acks: all
        retries: 3
        batch-size: 16384
        buffer-memory: 33554432
        linger-ms: PT5S
        delivery-timeout-ms: PT30S
        request-timeout-ms: PT5S
        compression-type: gzip
        max-inflight-requests-per-connection: 5
        enable-idempotence: true
        additional-properties: {}
      retry:
        max-attempts: 3
        initial-interval: PT1S
        multiplier: 2.0
        max-interval: PT30S
        randomization-factor: true

  # Outbox Configuration
  outbox:
    processing:
      interval: 10000  # 10 seconds - matches @Scheduled(fixedDelay = 10000)
    cleanup:
      retention-days: 7  # Matches the 7 days in OutboxEventProcessor
      cron: "0 0 2 * * *"  # Daily at 2 AM (default)